module.exports = [
    "abortion",
    "abortionist",
    "abuse",
    "advantage",
    "affirmative action",
    "age-old",
    "aggravate",
    "agony",
    "american values",
    "anarchist",
    "apologist",
    "assault rifle",
    "assault weapon",
    "astroturfer",
    "astroturfing",
    "atrocious",
    "backstabbingmaul",
    "bigot",
    "bourgeois",
    "brain washing",
    "brain-washing",
    "brainwashing",
    "brogressive",
    "bromance",
    "bully",
    "bureaucrat",
    "capitalist",
    "censorship",
    "child murder",
    "children",
    "cis",
    "cis white male",
    "class warfare",
    "collectivist",
    "communist",
    "confusing",
    "constitutionalist",
    "convenient",
    "coward",
    "creatard",
    "crooked",
    "cruel",
    "crushpound",
    "cuck",
    "cult",
    "cultural marxist",
    "damaging",
    "darwinism",
    "death tax",
    "deceiver",
    "defense of marriage",
    "denialist",
    "displeased",
    "divorce",
    "dizzying",
    "dreadful",
    "eliminate",
    "elitist",
    "entitlement",
    "epoch-making",
    "evangelical",
    "evil",
    "evotard",
    "exploit",
    "fair share",
    "fairness",
    "fake news",
    "family values",
    "fascism",
    "fascist",
    "feminazi",
    "frankenfood",
    "freedom fighter",
    "gay agenda",
    "ghetto",
    "grass roots",
    "grass-roots",
    "grassroots",
    "gun nut",
    "hard working",
    "hard-working",
    "harmful",
    "harsh",
    "hate",
    "health freedom",
    "heterophobia",
    "homofascism",
    "horrible",
    "illegal alien",
    "imperialist",
    "inconsiderate",
    "indoctrination",
    "inexorable",
    "inferior",
    "infidel",
    "insurgent",
    "interesting",
    "irritate",
    "islamist",
    "islamo-facist",
    "islamophobia",
    "jew",
    "jihadist",
    "job creator",
    "leftist",
    "libtard",
    "lies",
    "loser",
    "lying",
    "marxist",
    "men's rights activist",
    "mens rights",
    "mens rights activisit",
    "middle class",
    "misandrist",
    "misogynist",
    "modern feminism",
    "money-grubbing",
    "moral",
    "moral relativist",
    "mra",
    "muslim ban",
    "muslim travel ban",
    "natural marriage",
    "nazi",
    "neo-con",
    "neocon",
    "neoconservative",
    "neoliberal",
    "new age",
    "no child left behind",
    "no-good",
    "offend",
    "open minded",
    "open-minded",
    "ordeal",
    "outrageous",
    "outrageousness",
    "pagan",
    "patriot",
    "patriotic",
    "payback",
    "peace",
    "phenomenon",
    "play a leading role in",
    "play into the hands of",
    "politically correct",
    "populist",
    "privilage",
    "pro-death",
    "professional victim",
    "profitable",
    "progressive",
    "prosperity",
    "provoke",
    "punish",
    "purity",
    "put at a loss",
    "put up with",
    "putinization",
    "racist",
    "radfem",
    "radical feminist",
    "reactionary",
    "reform",
    "regime",
    "repulsive",
    "reverse racism",
    "reverse racist",
    "ride roughshod",
    "right wing",
    "right winger",
    "right-wing",
    "right-winger",
    "ruling class",
    "ruthless",
    "safe space",
    "satanist",
    "schadenfreude",
    "separatist",
    "severe",
    "shameful",
    "sheeple",
    "shill",
    "shocking",
    "sjw",
    "sniveling",
    "social justice",
    "social justice warrior",
    "socialist",
    "stand shoulder to shoulder with",
    "states rights",
    "states' rights",
    "status quo",
    "superior",
    "sustainable",
    "teabagger",
    "terrible",
    "terrorist",
    "thug",
    "toe the line",
    "tolerance",
    "traditional values",
    "tremendous",
    "triumphant",
    "troll",
    "troubled waters",
    "truly",
    "trustworthy",
    "unreliable",
    "unstable",
    "urban",
    "veritable",
    "veterans",
    "violence",
    "welfare",
    "welfare queen",
    "white knight",
    "white privilage",
    "will of the people",
    "wingnut",
    "workable",
    "working class",
    "working families",
    "working-class",
    "worthwhile",
    "zionist"
];