module.exports = [
    "banned",
    "banning",
    "behind the scenes",
    "blacklisted",
    "censored",
    "censorship",
    "conceals",
    "concealed",
    "concealing",
    "confessions",
    "confidential",
    "controversial",
    "cover-up",
    "covert",
    "forbid",
    "forbidden",
    "have you heard",
    "hidden",
    "insider",
    "insider’s scoop",
    "no one talks about",
    "off-the record",
    "secret",
    "secret agenda",
    "secret plot",
    "unbelievable",
    "underground",
    "what no one tells you"
];