module.exports = [
    "animosity",
    "arrogant",
    "bitterness",
    "blow up",
    "conniption",
    "disgusting",
    "enmity",
    "foul",
    "hissy fit",
    "ire",
    "irritation",
    "know-it-all",
    "loathsome",
    "mad",
    "obnoxious",
    "preposterous",
    "resentment",
    "revolting",
    "sick and tired",
    "smug",
    "snobforce-fed",
    "snooty",
    "snotty",
    "stuck up",
    "underhanded",
    "vexation"
];