module.exports = [
    "accurate",
    "always",
    "atheist",
    "atheists",
    "be subject to",
    "best",
    "bi-partisan",
    "bipartisan",
    "categorical",
    "certain",
    "christmas",
    "confident",
    "conservative",
    "constitute",
    "corporate",
    "corporates",
    "death",
    "dead",
    "definitely",
    "disadvantages",
    "disadvantaging",
    "disease",
    "diseases",
    "effective",
    "emphasize",
    "emphasise",
    "emphasizing",
    "emphasising",
    "enlightened",
    "enlightening",
    "ethical",
    "evolution",
    "expect",
    "freedom",
    "gmo",
    "historic",
    "holiday",
    "improved",
    "justice",
    "liberal",
    "magnificent",
    "millennial",
    "most",
    "most important",
    "natural",
    "neutral",
    "popular",
    "progress",
    "should",
    "state of the art",
    "state-of-the-art",
    "stringly recommend",
    "superb",
    "virtual",
    "wild"
];