module.exports = [
    "a cut above",
    "absolutely",
    "accurate",
    "adaptable",
    "advantage",
    "always",
    "approving",
    "assured",
    "astonishing",
    "astounded",
    "authentic",
    "bargain",
    "certain",
    "certainly",
    "clarity",
    "confident",
    "conscientious",
    "convenient",
    "definitely",
    "delighted",
    "easy",
    "ecstatic",
    "effective",
    "emphasize",
    "excellent",
    "extremely",
    "first ever",
    "freedom",
    "fulfilled",
    "genuine",
    "guaranteed",
    "highly effective",
    "highly likely",
    "honest",
    "honored",
    "humility",
    "instantly",
    "introducing",
    "investment",
    "privileged",
    "relaxed",
    "reliable",
    "responsible",
    "secure",
    "self-sufficient",
    "solid",
    "stable",
    "supported",
    "supportive",
    "sure",
    "transparency",
    "trusting",
    "truthful"
];