module.exports = [
    "bargain",
    "deadline",
    "discount",
    "explode",
    "extra",
    "fortune",
    "freebie",
    "immediately",
    "imminently",
    "instant savings",
    "instantly",
    "jackpot",
    "left behind",
    "limited",
    "magical",
    "magnificent",
    "miracle",
    "missing out",
    "most important",
    "profitable",
    "proven",
    "quick",
    "reduced",
    "remarkable",
    "results",
    "revolutionary",
    "safe",
    "save",
    "seize",
    "sensational",
    "should",
    "skyrocket",
    "startling",
    "strongly agree",
    "strongly recommend",
    "strongly suggest",
    "superb",
    "superior",
    "tremendous",
    "truly",
    "trustworthy",
    "urge",
    "worthwhile"
];